### PR TITLE
Revert "rustfmt is too pedantic"

### PR DESCRIPTION
**Pull request by MarijnS95**
Thanks for consulting with me!

### CODE REVIEW

**Comment by kornelski** [comment]
Do you mean I should have consulted with you before removing rustfmt step?

**Comment by MarijnS95** [comment]
@kornelski a heads-up/ping would have been nice so that I couple point out this alternative.

It's not so much the CI but afaik most contributors/projects use rustfmt, and it's really annoying if one gets a bunch of unrelated changes in a repo when they run rustfmt before sending in a contribution. That's exactly what this CI step prevents, and why I think it's better to change rustfmt defaults than to disable it outright?

**Comment by Mercesa** [comment]
In my experience projects that do not have `rustfmt` are an instant turn-off, as @MarijnS95 mentioned most projects would use this regardless. I have auto-format on in my `vscode` and if I would contribute to this project, it would potentially show up formatting changes in PRs which is annoying.

**Comment by kornelski** [comment]
My take is that `rustfmt` is not good enough to be used uncritically. 

`gofmt` is great. It focuses on fixing formatting mistakes, but leaves code layout mostly unharmed (human judgement about things like 1-line vs multiline expressions is preserved). OTOH `rustfmt` is an aggressive canonicalizer that intentionally replaces human-crafted code layout with inflexible heuristics incapable of having common sense. This is not merely a bug in `rustfmt`, but a fundamental flaw coming from its design principle of prioritizing ability of formatting mangled machine-generated code over carefully formatting human-written code.

Requiring `rustfmt` means sometimes code needs to be made worse and less readable, or at least sprinkled with `rustfmt::skip` to limits its damage. Requiring `rustfmt` in CI means that perfectly readable code may be rejected. 

I think use of `rustfmt` is perpetuated by a fallacy of "we need _something_, `rustfmt` is something, therefore we need `rustfmt`". Currently the Rust ecosystem doesn't have a good formatter for human-written code, and I'd prefer to use no tool for this than to use a wrong tool. 

I also think it's destructive to have auto reformatting with `rustfmt` enabled, and I ask people not to do that.

**Comment by MarijnS95** [comment]
My view is completely the inverse of that. `rustfmt` is one of the best tools for formatting out there, especially compared to something like `clang-format` which actively harm code.
(Perhaps `gofmt` is even better, I have no experience with that)

This project already sits extremely close to what `rustfmt` outputs, even before https://github.com/app-dirs-rs/app_dirs2/pull/25 landed - which really only cleaned up some _inconsistent_ spacing in `cfg` and reordered some `use` statements to be alphabetical: both which stand out as a sore thumb while contributing to a project.
(EDIT: I agree the original writing of `let is_valid =` is nice on the eyes, but that's one isolated case [and reverted by this PR] compared to the many other changes it _got right_.)

I am a human, and I don't want to waste time prettifying my code. Prettifying first and foremost means being consistent with the codebase at hand. After writing a contribution I just want to hit a hotkey or `cargo fmt` and not have to deal with manually changing indentation, newlining and trailing comma's while preparing a change for upstreaming. More so, I don't want to read code that is actively wrong in these regards. Finally, as a maintainer of other crates, I don't want to look out for it in PRs either, that's the job of the CI.

All in all I think there's more benefit to having `rustfmt`, and in the few areas where one/you doesn't agree with the output it can be reconfigured (IMO this change is easily readable regardless of whether it resides on one or five lines). I've never seen `rustfmt::skip` in a codebase yet but maybe I'm not looking hard enough.

**Comment by kornelski** [comment]
It's not possible to configure `rustfmt` to prevent it from exploding 1-liners unnecessarily, or spaghettifying multi-line expressions into one line. It overrides the layout based on its heuristics, which are very naive. There is no amount of configuration that makes rustfmt palatable, because it's not a formatter, it's a canonicalizer.

You haven't seen `rustfmt::skip` used, because it's not even that useful. It itself is ugly, can't be applied to whole files, and most people prefer to tolerate clumsily-formatted code than having a discussion about it.

I think it's unfair to reject in CI nicely-formatted PRs because they are not absolutely exactly (mis)formatted in the only possible way that `rustfmt` will permit.

**Review by Jasper-Bekkers — APPROVED** [review]

**Comment by MarijnS95** [comment]
@kornelski I take it we're done discussing this? Don't be surprised when PRs show up that reformat this when running `cargo fmt` and assuming the drive-by fix to be a missed fluke in the repo :wink:

**Comment by kornelski** [comment]
Yeah, I can't help that. Sadly, even `Ignore` in rustfmt config doesn't work yet (unstable).

**Pull request closed without merging**
